### ISSUE TITLE
"experiment" is misspelled

### ISSUE THREAD

**Issue by blahquabats** [wckaratekid/TheRealMazeBot#1]
I was terrified to discover "experiment" spelled as "expirament" on the home page. 

Please respond!!!!!!

**Comment by rtanase2** [comment]
Oh my gosh! This is why we should never push out code at 4AM! Will fix immediately!

**Comment by rtanase2** [comment]
Bug fixed in commit 857d01bc6c00da9063f0e1f6af20f9327113ce2e
